# Generated by Django 4.2.4 on 2023-09-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('escala', 'Escala'), ('demanda', 'Demanda'), ('dsp', 'DSP')], max_length=10, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('datahorainicial', models.DateTimeField(blank=True, null=True)),
                ('datahorafinal', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.TimeField(blank=True, null=True)),
                ('documentacao', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Militar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=100, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('postgrad', models.CharField(blank=True, choices=[('sd2cl', 'SD 2ª Classe BM'), ('sd', 'SD BM'), ('cb', 'CB BM'), ('3sgt', '3º SGT BM'), ('2sgt', '2º SGT BM'), ('1sgt', '1º SGT BM'), ('subten', 'SUB TEN BM'), ('2ten', '2º TEN BM'), ('1ten', '1º TEN BM'), ('cap', 'CAP BM'), ('maj', 'MAJ BM'), ('tencel', 'TEN CEL BM'), ('cel', 'CEL BM')], max_length=10, null=True)),
                ('local', models.CharField(blank=True, choices=[('acf', 'ACF'), ('sdts1', 'SDTS 1'), ('sdts2', 'SDTS 2'), ('sdts3', 'SDTS 3'), ('nts', 'NTS'), ('sdal1', 'SDAL 1'), ('sdal2', 'SDAL 2'), ('sdal3', 'SDAL 3'), ('sdal4', 'SDAL 4')], max_length=10, null=True)),
                ('empenhos', models.ManyToManyField(blank=True, related_name='militares', to='cadastros.empenho')),
            ],
        ),
        migrations.CreateModel(
            name='Obs_emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('empenho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obs_empenho', to='cadastros.empenho')),
                ('militar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='obs_militar', to='cadastros.militar')),
            ],
        ),
    ]
