# Generated by Django 4.2.8 on 2024-05-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='empenhos',
            field=models.ManyToManyField(blank=True, null=True, related_name='militares', to='cadastros.empenho'),
        ),
    ]
