# Generated by Django 4.2.4 on 2023-09-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenho',
            name='duracao',
        ),
        migrations.AddField(
            model_name='empenho',
            name='duracao_em_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='militar',
            name='local',
            field=models.CharField(blank=True, choices=[('acf', 'ACF'), ('sdts1', 'SDTS 1'), ('sdts2', 'SDTS 2'), ('sdts3', 'SDTS 3'), ('nts', 'NTS'), ('sdal1', 'SDAL 1'), ('sdal2', 'SDAL 2'), ('sdal3', 'SDAL 3'), ('sdal4', 'SDAL 4'), ('sec', 'Secretaria')], max_length=10, null=True),
        ),
    ]
