# Generated by Django 4.2.4 on 2023-09-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_empenho_duracao_empenho_duracao_em_minutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='militar',
            name='empenhos_em_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='militar',
            name='qtd_empenhos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
