# Generated by Django 4.2.4 on 2023-09-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_militar_empenhos_em_minutos_militar_qtd_empenhos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='postgrad',
            field=models.CharField(blank=True, choices=[('sd2cl', 'Sd 2ª Classe BM'), ('sd', 'Sd BM'), ('cb', 'Cb BM'), ('3sgt', '3º Sgt BM'), ('2sgt', '2º Sgt BM'), ('1sgt', '1º Sgt BM'), ('subten', 'Sub Ten BM'), ('2ten', '2º Ten BM'), ('1ten', '1º Ten BM'), ('cap', 'Cap BM'), ('maj', 'Maj BM'), ('tencel', 'Ten Cel BM'), ('cel', 'Cel BM')], max_length=10, null=True),
        ),
    ]
