# Generated by Django 4.2.4 on 2023-09-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_militar_postgrad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenho',
            name='duracao_em_minutos',
        ),
        migrations.AddField(
            model_name='empenho',
            name='duracao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
