# Generated by Django 4.2.4 on 2023-09-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_remove_empenho_duracao_em_minutos_empenho_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empenho',
            name='duracao',
        ),
        migrations.AddField(
            model_name='empenho',
            name='duracao_em_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
