# Generated by Django 4.2.4 on 2023-09-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_rename_empenhos_em_minutos_militar_empenhos_minutos_verde_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empenho',
            old_name='duracao_em_minutos',
            new_name='duracao_em_minutos_atipica',
        ),
        migrations.RenameField(
            model_name='militar',
            old_name='empenhos_minutos_verde',
            new_name='empenhos_minutos_atipica',
        ),
        migrations.RenameField(
            model_name='militar',
            old_name='empenhos_minutos_vermelha',
            new_name='empenhos_minutos_tipica',
        ),
        migrations.RenameField(
            model_name='militar',
            old_name='qtd_empenhos_verde',
            new_name='qtd_empenhos_atipica',
        ),
        migrations.RenameField(
            model_name='militar',
            old_name='qtd_empenhos_vermelha',
            new_name='qtd_empenhos_tipica',
        ),
        migrations.AddField(
            model_name='empenho',
            name='duracao_em_minutos_tipica',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
