# Generated by Django 4.2.4 on 2023-11-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_rename_duracao_em_minutos_empenho_duracao_em_minutos_atipica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empenho',
            name='classe',
            field=models.CharField(blank=True, choices=[('tipico', 'Típico'), ('atipico', 'Atipico')], max_length=10, null=True),
        ),
    ]
