# Generated by Django 4.2.4 on 2023-11-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_alter_empenho_classe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='militar',
            old_name='qtd_empenhos_atipica',
            new_name='qtd_empenhos',
        ),
        migrations.RemoveField(
            model_name='empenho',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='militar',
            name='qtd_empenhos_tipica',
        ),
    ]
