# Generated by Django 4.2.4 on 2023-12-13 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_rename_qtd_empenhos_atipica_militar_qtd_empenhos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militar',
            name='empenhos',
            field=models.ManyToManyField(related_name='militares', to='cadastros.empenho'),
        ),
    ]
