# Generated by Django 4.2.4 on 2023-09-07 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0006_remove_empenho_duracao_empenho_duracao_em_minutos'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndispMilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('ferias', 'Férias'), ('licenca', 'Licença'), ('dispensa', 'Dispensa'), ('outros', 'Outros')], max_length=10, null=True)),
                ('datainicial', models.DateField(blank=True, null=True)),
                ('datafinal', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('militar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='indisp_militar', to='cadastros.militar')),
            ],
        ),
    ]
