# Generated by Django 4.2.4 on 2023-09-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indisponibilidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaZero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classe', models.CharField(blank=True, choices=[('feriado', 'Feriado'), ('pontof', 'Ponto Facultativo'), ('libaracao', 'Libaracao')], max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('horainicial', models.TimeField(blank=True, null=True)),
                ('horafinal', models.TimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=True)),
            ],
        ),
    ]
