# Generated by Django 4.2.4 on 2023-12-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_rename_qtd_empenhos_atipica_militar_qtd_empenhos_and_more'),
        ('indisponibilidade', '0002_diazero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diazero',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indispmilitar',
            name='datafinal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indispmilitar',
            name='datainicial',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indispmilitar',
            name='militar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indisp_militar', to='cadastros.militar'),
        ),
    ]
